ibm_cloud_fail_over/__init__.py,sha256=8C0qkiHbfDmglGpuN3bpxe1mIJ479eTtlAv6VsKA9HU,586
ibm_cloud_fail_over/ibm_cloud_fail_over.py,sha256=YaZshY4teHwRZIGr8GugninzG2TDN0UlVbl6-Uv9bLY,41862
ibm_cloud_fail_over-1.0.19.dist-info/METADATA,sha256=6l8J5iN8wW9R27ycCPxpJba33Byf49PDCRAHCuvzmWA,10786
ibm_cloud_fail_over-1.0.19.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
ibm_cloud_fail_over-1.0.19.dist-info/licenses/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
ibm_cloud_fail_over-1.0.19.dist-info/RECORD,,
